# Taken from https://circleci.com/orbs/registry/orb/react-native-community/react-native

jobs:
  analyse_js:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
#      - run:
#          command: yarn eslint
#          name: Run ESLint
#      - run:
#          command: yarn flow
#          name: Flow
      - run:
          command: yarn jest
          name: Jest
  checkout_code:
    executor:
      name: rn/linux_js
      node_version: '10'
    steps:
      - checkout
      - persist_to_workspace:
          paths: .
          root: .
  fastlane_android_release:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          command: echo
          name: Run Fastlane
  fastlane_ios_release:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          command: echo 1
          name: Run Fastlane
orbs:
  rn: react-native-community/react-native@1.0.0
version: 2.1
workflows:
  test:
    jobs:
      - checkout_code
      - analyse_js:
          requires:
            - checkout_code
      - rn/android_build:
          build_type: debug
          name: build_android_debug
          project_path: android
          requires:
            - analyse_js
      - rn/android_build:
          build_type: release
          name: build_android_release
          project_path: android
          requires:
            - analyse_js
      - rn/android_test:
          detox_configuration: android.emu.release
          requires:
            - build_android_release
      - rn/ios_build:
          build_configuration: Release
          device: iPhone X
          name: build_ios_release
          node_version: '10'
          project_path: ios/codeAgainstCorona.xcodeproj
          requires:
            - analyse_js
          scheme: hamagen
      - rn/ios_build_and_test:
          build_configuration: Release
          detox_configuration: ios.sim.release
          device: iPhone X
          node_version: '10'
          project_path: ios/codeAgainstCorona.xcodeproj
          requires:
            - analyse_js
          scheme: hamagen
      - fastlane_android_release:
          requires:
            - rn/android_test
      - fastlane_ios_release:
          requires:
            - rn/ios_build_and_test
